MVCCrud/MVCCrud/Models/ViewModels/ClienteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCCrud.Models.ViewModels
{
    public class ClienteViewModel
    {
        public int id_cli { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string nombre_cli { get; set; }

        [Required]
        [StringLength(10)]
        [Display(Name = "Cedula")]
        public string cedula_cli { get; set; }

        [Required]
        [StringLength(80)]
  
        [Display(Name = "Correo electronico")]
        public string correo_cli { get; set; }

        [Required]
        [Display(Name = "Fecha de nacimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat (DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public DateTime fechaNacimiento { get; set; }

        
        [Display(Name = "Imagen")]
        public byte[] foto { get; set; }
    }
}

MVCCrud/MVCCrud/Models/cliente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cli { get; set; }
        public string nombre_cli { get; set; }
        public string cedula_cli { get; set; }
        public string correo_cli { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public byte[] foto { get; set; }
    }
}

MVCCrud/MVCCrud/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MVCCrud.Models;
using MVCCrud.Models.ViewModels;

namespace MVCCrud.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            List<ListClienteViewModel> listaClientes;
            using (facturaEntities db = new facturaEntities())
            {
                listaClientes = ( from c in db.cliente
                                  select new ListClienteViewModel
                                  {
                                      id_cli = c.id_cli,
                                      nombre_cli = c.nombre_cli,
                                      cedula_cli = c.cedula_cli,
                                      correo_cli = c.correo_cli
                                  }).ToList();
            }
                return View(listaClientes);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(ClienteViewModel clienteModel)
        {
            try
            {
                //Validar el modelo
                if (ModelState.IsValid)
                {
                    HttpPostedFileBase pfb = Request.Files[0];
                    WebImage img = new WebImage(pfb.InputStream);
                    clienteModel.foto = img.GetBytes();
                    //Conexion a la base de datos y paso de datos del modelo a un
                    //objeto de tipo cliente
                    using(facturaEntities db = new facturaEntities())
                    {
                        var oCliente = new cliente();
                        oCliente.nombre_cli = clienteModel.nombre_cli;
                        oCliente.cedula_cli = clienteModel.cedula_cli;
                        oCliente.correo_cli = clienteModel.correo_cli;
                        oCliente.fechaNacimiento = clienteModel.fechaNacimiento;
                        oCliente.foto = clienteModel.foto;

                        //Almacenar en la base de datos el objeto cliente
                        db.cliente.Add(oCliente);
                        db.SaveChanges();
                    }
                    return Redirect("~/Cliente/");
                }
                return View(clienteModel);
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id) //parametro id
        {
            ClienteViewModel model = new ClienteViewModel();
            using (facturaEntities db = new facturaEntities())
            {
                var oCliente = db.cliente.Find(id);
                model.nombre_cli = oCliente.nombre_cli;
                model.cedula_cli = oCliente.cedula_cli;
                model.correo_cli = oCliente.correo_cli;
                model.fechaNacimiento = (DateTime)oCliente.fechaNacimiento;
                //Dato agregado recien 
                model.id_cli = oCliente.id_cli;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(ClienteViewModel clienteModel) //parametro id
        {
            try
            {
                //Validando el formulario
                if (ModelState.IsValid)
                {
                    using (facturaEntities db = new facturaEntities())
                    {
                        //Se busca el cliente para actualizar
                        var oCliente = db.cliente.Find(clienteModel.id_cli);
                        oCliente.nombre_cli = clienteModel.nombre_cli;
                        oCliente.cedula_cli = clienteModel.cedula_cli;
                        oCliente.correo_cli = clienteModel.correo_cli;
                        oCliente.fechaNacimiento = (DateTime)clienteModel.fechaNacimiento;

                        //Envair los datos para que sean actualizados
                        //Se mantiene el estado, se haga la actualizacion y que no se vuelva agregar
                        db.Entry(oCliente).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/Cliente/");
                }

                return View(clienteModel);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Eliminar(int id)
        {
            using(facturaEntities db = new facturaEntities())
            {
                var oCliente = db.cliente.Find(id);
                db.cliente.Remove(oCliente);
                db.SaveChanges();
            }

            return Redirect("~/Cliente/");
        }
    }
}

MVCCrud/MVCCrud/Views/Cliente/Editar.cshtml
<!--recibir el modelo-->
@model  MVCCrud.Models.ViewModels.ClienteViewModel
@{
    ViewBag.Title = "Editar datos del cliente";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "cliente", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.id_cli) <!--ID OCULTO-->
            <div>
                @Html.LabelFor(d => d.nombre_cli)
                @Html.TextBoxFor(d => d.nombre_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.nombre_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.cedula_cli)
                @Html.TextBoxFor(d => d.cedula_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.cedula_cli, null, new { @class = "red" })
            </div>


            <div>
                @Html.LabelFor(d => d.correo_cli)
                @Html.TextBoxFor(d => d.correo_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.correo_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.fechaNacimiento) <br />
                @Html.EditorFor(d => d.fechaNacimiento, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.fechaNacimiento, null, new { @class = "red" })
            </div>
            <br />
            <br />
            <div>
                <input value="Actualizar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

@section Scripts {
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#fechaNacimiento").datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                yearRange: '-100:+0'
            });
        });
    </script>
}

MVCCrud/MVCCrud/Views/Cliente/Index.cshtml
@model List<MVCCrud.Models.ViewModels.ListClienteViewModel>
@{
    ViewBag.Title = "Clientes";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">

        <div class="row" style="text-align:right; padding:10px">
            <a href="~/Cliente/Nuevo" class="btn btn-primary">Agregar</a>
        </div>

        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Cedula</th>
                <th>Correo</th>
            </tr>
            @foreach (var oElemento in Model)
            {
                <tr>
                    <td>@oElemento.id_cli</td>
                    <td>@oElemento.nombre_cli</td>
                    <td>@oElemento.cedula_cli</td>
                    <td>@oElemento.correo_cli</td>
                    
                    <td>
                        <a class="btn btn-default" href="@Url.Action("Editar", "Cliente", new {id=@oElemento.id_cli})">Editar</a>
                        <a class="btn btn-danger" href="@Url.Action("Eliminar", "Cliente", new {id=@oElemento.id_cli})" onclick = "return smsConfirmacion()">
                        Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>


<script>
    function smsConfirmacion() {
        if (confirm("¿Esta seguro de eliminar este registro?") == true) {
            return true;
            } else {
                return false;
            }
         }
</script>      

MVCCrud/MVCCrud/Views/Cliente/Nuevo.cshtml
@model MVCCrud.Models.ViewModels.ClienteViewModel
@{
    ViewBag.Title = "Datos del Cliente";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "cliente", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.nombre_cli)
                @Html.TextBoxFor(d => d.nombre_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.nombre_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.cedula_cli)
                @Html.TextBoxFor(d => d.cedula_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.cedula_cli, null, new { @class = "red" })
            </div>


            <div>
                @Html.LabelFor(d => d.correo_cli)
                @Html.TextBoxFor(d => d.correo_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.correo_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.fechaNacimiento) <br />
                @Html.EditorFor(d => d.fechaNacimiento, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.fechaNacimiento, null, new { @class = "red" })
            </div>
            <br />
            <br />
            <div>
                @Html.LabelFor(d => d.foto, htmlAttributes: new { @class = "control-label" })
                <br />
                <br />
                <input type="file" name="imageload" />
                <br />
                <br />
                @Html.ValidationMessageFor(d => d.foto, "", new { @class = "red" })
            </div>
            <br />
            <br />
            <div>
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

@section Scripts {
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#fechaNacimiento").datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true,
                yearRange: '-100:+0'
            });
        });
    </script>
}